### ISSUE TITLE
Publish on OpenVSX Marketplace

### ISSUE THREAD

**Issue by r0l1** [omBratteng/vscode-nftables#2]
Arch Linux (Linux based operating system distribution) has decided to switch the marketplace for extensions from the [MS Visual Studio Marketplace](https://marketplace.visualstudio.com) to [OpenVSX](https://open-vsx.org/) in [this commit](https://git.archlinux.org/svntogit/community.git/commit/trunk?id=b62a02ec645f16528c0269faf12e362a55efda75).

[Here](https://www.gitpod.io/blog/open-vsx/) are some more details about OpenVSX, its goal, and why it was created

Could you please [release this plugin](https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php) on the OpenVSX marketplace?
Thank you!

**Comment by omBratteng** [comment]
The plugin has now been published at https://open-vsx.org/extension/omBratteng/nftables
And I just realised that I misspelled the name before, and I have corrected it on both VS Marketplace and OpenVSX. So it's published under both, but going forward only the correct spelling is used

**Comment by r0l1** [comment]
Thanks for the fast response and fix!

**Comment by omBratteng** [comment]
Already started https://github.com/EclipseFdn/open-vsx.org/issues/252

**Comment by omBratteng** [comment]
And claimed.

**Comment by r0l1** [comment]
Thanks!
