### ISSUE TITLE
Formatting issue with multi-line lists

### ISSUE THREAD

**Issue by jgraichen** [omBratteng/vscode-nftables#313]
The following example will have it's last line indented, which can mess all following indents:

```nft
chain default {
    ip protocol icmp icmp type {
        destination-unreachable,
        echo-request,
        parameter-problem,
        router-advertisement,
        router-solicitation,
        time-exceeded,
    } counter accept   # <===
}
```

After formatting:

```nft
chain default {
    ip protocol icmp icmp type {
        destination-unreachable,
        echo-request,
        parameter-problem,
        router-advertisement,
        router-solicitation,
        time-exceeded,
        } counter accept   # <===
    }
```

What would be the recommended workaround?

**Comment by andreas51** [comment]
Currently the formatter ignores closing braces which are not at the end of a line.
A quick workaround would be to enter a line break before "counter accept".
I've added PR #316 to allow closing braces before the end of a line.

**Comment by jgraichen** [comment]
Thank you a lot! It works like a charm now.

**Comment by omBratteng** [comment]
Perfect 👍🏻
